name: Vinicius Trindade
description: System Analyst and Web Developer
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: false

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: contact@viniciustrindade.com.br
  facebook: 
  flickr: 
  github: viniblessing
  instagram: 
  linkedin: viniciustrindade
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: users/889849/viniblessing # your stackoverflow profile, e.g. "users/50476/bart-kiers"

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://viniblessing.github.io'
google_analytics: 'UA-27535758-1'
disqus: true
disqus_shortname: 'viniblessing'

# Details for the RSS feed generator
url:            'http://viniblessing.github.io'
author:         'Vinicius Trindade'
authorTwitter:  'viniblessing'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
